spring:
  application:
    name: hackathon
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5450/hackathon_dev
    username: hackathon
    password: password