ALTER TABLE city
    DROP CONSTRAINT fk_city_on_aid;

CREATE TABLE asset_type
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mode_of_travel  SMALLINT,
    water_capacity  BIGINT,
    food_capacity   BIGINT,
    aid_capacity    BIGINT,
    fuel_usage_rate DOUBLE PRECISION,
    speed           BIGINT,
    CONSTRAINT pk_assettype PRIMARY KEY (id)
);

CREATE TABLE medical
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    on_hand    BIGINT,
    usage_rate DOUBLE PRECISION,
    capacity   BIGINT,
    CONSTRAINT pk_medical PRIMARY KEY (id)
);

ALTER TABLE asset
    ADD asset_type_id BIGINT;

ALTER TABLE asset
    ADD food_onhand BIGINT;

ALTER TABLE asset
    ADD medical_onhand BIGINT;

ALTER TABLE asset
    ADD status SMALLINT;

ALTER TABLE asset
    ADD travel_days_remaining BIGINT;

ALTER TABLE asset
    ADD water_onhand BIGINT;

ALTER TABLE city
    ADD medical_id BIGINT;

ALTER TABLE asset
    ADD CONSTRAINT FK_ASSET_ON_ASSETTYPE FOREIGN KEY (asset_type_id) REFERENCES asset_type (id);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_MEDICAL FOREIGN KEY (medical_id) REFERENCES medical (id);

DROP TABLE aid CASCADE;

ALTER TABLE asset
    DROP COLUMN aid_capacity;

ALTER TABLE asset
    DROP COLUMN food_capacity;

ALTER TABLE asset
    DROP COLUMN fuel_usage_rate;

ALTER TABLE asset
    DROP COLUMN speed;

ALTER TABLE asset
    DROP COLUMN water_capacity;

ALTER TABLE city
    DROP COLUMN aid_id;