CREATE TABLE city
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name  VARCHAR(255),
    population INTEGER                                NOT NULL,
    x_axis     FLOAT                                 NOT NULL,
    y_axis     FLOAT                                 NOT NULL,
    fuel       INTEGER                                 NOT NULL,
    water_id   BIGINT,
    aid_id     BIGINT,
    food_id    BIGINT,
    CONSTRAINT pk_city PRIMARY KEY (id)
);