CREATE TABLE city
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name  VARCHAR(255),
    population INTEGER                                 NOT NULL,
    x_axis     FLOAT                                 NOT NULL,
    y_axis     FLOAT                                 NOT NULL,
    fuel       INTEGER                                 NOT NULL,
    water_id   BIGINT,
    aid_id     BIGINT,
    food_id    BIGINT,
    CONSTRAINT pk_city PRIMARY KEY (id)
);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (1, 'Coral Reef Community',150000, 0.88, 0.155, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (2, 'Turtleback Island', 30000, 0.125, 0.71, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (3, 'Sunset Cove District', 225000, 0.595, 0.49, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (4, 'Mangrove Coastline', 350000, 0.425, 0.374, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (5, 'Lagoon Bay Village', 130000, 0.55, 0.285, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (6, 'TF Main', 0, 0.485, 0.385, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (7, 'Stormbreaker Cliffs', 50000, 0.655, 0.36, 0);
INSERT INTO public.city (id, city_name, population, x_axis, y_axis, fuel)
VALUES (8, 'Moonlit Cove', 80000, 0.58, 0.365, 0);