CREATE TABLE IF NOT EXISTS aid
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    on_hand    BIGINT,
    usage_rate DOUBLE PRECISION,
    capacity   BIGINT,
    CONSTRAINT pk_aid PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS city
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name  VARCHAR(255),
    population INTEGER                                 NOT NULL,
    x_axis     INTEGER                                 NOT NULL,
    y_axis     INTEGER                                 NOT NULL,
    fuel       INTEGER                                 NOT NULL,
    water_id   BIGINT,
    aid_id     BIGINT,
    food_id    BIGINT,
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS food
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    on_hand    BIGINT,
    usage_rate DOUBLE PRECISION,
    capacity   BIGINT,
    CONSTRAINT pk_food PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS water
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    on_hand    BIGINT,
    usage_rate DOUBLE PRECISION,
    capacity   BIGINT,
    CONSTRAINT pk_water PRIMARY KEY (id)
);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_AID FOREIGN KEY (aid_id) REFERENCES aid (id);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_FOOD FOREIGN KEY (food_id) REFERENCES food (id);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_WATER FOREIGN KEY (water_id) REFERENCES water (id);