CREATE TABLE IF NOT EXISTS asset
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_id     BIGINT,
    water_capacity  BIGINT,
    food_capacity   BIGINT,
    aid_capacity    BIGINT,
    fuel_usage_rate DOUBLE PRECISION,
    speed           BIGINT,
    CONSTRAINT pk_asset PRIMARY KEY (id)
);


ALTER TABLE asset
    ADD CONSTRAINT FK_ASSET_ON_LOCATION FOREIGN KEY (location_id) REFERENCES city (id);
